In [104]:
import requests
import pandas as pd

In [105]:
# Company Ticker
company_tik = "QCOM"

In [106]:
#API Key
api_key = "BJNWYM8ELVHG6ZWG"

In [107]:
#### API call for Income_statement ####
url = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={company_tik}&apikey={api_key}&datatype=csv'
r = requests.get(url)
income_data = r.json()

print(income_data)

{'symbol': 'QCOM', 'annualReports': [{'fiscalDateEnding': '2022-09-30', 'reportedCurrency': 'USD', 'grossProfit': '25565000000', 'totalRevenue': '44200000000', 'costOfRevenue': '18635000000', 'costofGoodsAndServicesSold': '18635000000', 'operatingIncome': '15860000000', 'sellingGeneralAndAdministrative': '2570000000', 'researchAndDevelopment': '8194000000', 'operatingExpenses': '11246000000', 'investmentIncomeNet': '91000000', 'netInterestIncome': '-490000000', 'interestIncome': '91000000', 'interestExpense': '490000000', 'nonInterestIncome': '19000000', 'otherNonOperatingIncome': '-372000000', 'depreciation': '1300000000', 'depreciationAndAmortization': '482000000', 'incomeBeforeTax': '14948000000', 'incomeTaxExpense': '2012000000', 'interestAndDebtExpense': '490000000', 'netIncomeFromContinuingOperations': '12986000000', 'comprehensiveIncomeNetOfTax': '12786000000', 'ebit': '15438000000', 'ebitda': '15920000000', 'netIncome': '12936000000'}, {'fiscalDateEnding': '2021-09-30', 'reportedCurrency': 'USD', 'grossProfit': '19304000000', 'totalRevenue': '33566000000', 'costOfRevenue': '14262000000', 'costofGoodsAndServicesSold': '14262000000', 'operatingIncome': '9789000000', 'sellingGeneralAndAdministrative': '2339000000', 'researchAndDevelopment': '7176000000', 'operatingExpenses': '10057000000', 'investmentIncomeNet': '83000000', 'netInterestIncome': '-559000000', 'interestIncome': '83000000', 'interestExpense': '559000000', 'nonInterestIncome': '-32000000', 'otherNonOperatingIncome': '1044000000', 'depreciation': '1000000000', 'depreciationAndAmortization': '537000000', 'incomeBeforeTax': '10274000000', 'incomeTaxExpense': '1231000000', 'interestAndDebtExpense': '559000000', 'netIncomeFromContinuingOperations': '9043000000', 'comprehensiveIncomeNetOfTax': '8964000000', 'ebit': '10833000000', 'ebitda': '11370000000', 'netIncome': '9043000000'}, {'fiscalDateEnding': '2020-09-30', 'reportedCurrency': 'USD', 'grossProfit': '14276000000', 'totalRevenue': '23531000000', 'costOfRevenue': '9255000000', 'costofGoodsAndServicesSold': '9255000000', 'operatingIncome': '6255000000', 'sellingGeneralAndAdministrative': '2074000000', 'researchAndDevelopment': '5975000000', 'operatingExpenses': '8642000000', 'investmentIncomeNet': '156000000', 'netInterestIncome': '-602000000', 'interestIncome': '156000000', 'interestExpense': '602000000', 'nonInterestIncome': '-8000000', 'otherNonOperatingIncome': '66000000', 'depreciation': '772000000', 'depreciationAndAmortization': '621000000', 'incomeBeforeTax': '5719000000', 'incomeTaxExpense': '521000000', 'interestAndDebtExpense': '585000000', 'netIncomeFromContinuingOperations': '5198000000', 'comprehensiveIncomeNetOfTax': '5305000000', 'ebit': '6321000000', 'ebitda': '6942000000', 'netIncome': '5198000000'}, {'fiscalDateEnding': '2019-09-30', 'reportedCurrency': 'USD', 'grossProfit': '15674000000', 'totalRevenue': '24273000000', 'costOfRevenue': '8599000000', 'costofGoodsAndServicesSold': '8599000000', 'operatingIncome': '7667000000', 'sellingGeneralAndAdministrative': '2195000000', 'researchAndDevelopment': '5398000000', 'operatingExpenses': '8554000000', 'investmentIncomeNet': '316000000', 'netInterestIncome': '-627000000', 'interestIncome': '316000000', 'interestExpense': '627000000', 'nonInterestIncome': '11000000', 'otherNonOperatingIncome': '441000000', 'depreciation': '674000000', 'depreciationAndAmortization': '727000000', 'incomeBeforeTax': '7481000000', 'incomeTaxExpense': '3095000000', 'interestAndDebtExpense': '627000000', 'netIncomeFromContinuingOperations': '4386000000', 'comprehensiveIncomeNetOfTax': '4272000000', 'ebit': '8108000000', 'ebitda': '8835000000', 'netIncome': '4386000000'}, {'fiscalDateEnding': '2018-09-30', 'reportedCurrency': 'USD', 'grossProfit': '12367000000', 'totalRevenue': '22611000000', 'costOfRevenue': '10244000000', 'costofGoodsAndServicesSold': '10244000000', 'operatingIncome': '621000000', 'sellingGeneralAndAdministrative': '2986000000', 'researchAndDevelopment': '5625000000', 'operatingExpenses': '10029000000', 'investmentIncomeNet': '625000000', 'netInterestIncome': '-768000000', 'interestIncome': '625000000', 'interestExpense': '768000000', 'nonInterestIncome': '37000000', 'otherNonOperatingIncome': '539000000', 'depreciation': '776000000', 'depreciationAndAmortization': '785000000', 'incomeBeforeTax': '392000000', 'incomeTaxExpense': '5356000000', 'interestAndDebtExpense': '768000000', 'netIncomeFromContinuingOperations': '-4864000000', 'comprehensiveIncomeNetOfTax': '-5083000000', 'ebit': '1160000000', 'ebitda': '1945000000', 'netIncome': '-4964000000'}], 'quarterlyReports': [{'fiscalDateEnding': '2023-06-30', 'reportedCurrency': 'USD', 'grossProfit': '4659000000', 'totalRevenue': '8451000000', 'costOfRevenue': '3792000000', 'costofGoodsAndServicesSold': '3792000000', 'operatingIncome': '1823000000', 'sellingGeneralAndAdministrative': '618000000', 'researchAndDevelopment': '2222000000', 'operatingExpenses': '2840000000', 'investmentIncomeNet': '79000000', 'netInterestIncome': '-172000000', 'interestIncome': '79000000', 'interestExpense': '172000000', 'nonInterestIncome': 'None', 'otherNonOperatingIncome': '4000000', 'depreciation': 'None', 'depreciationAndAmortization': 'None', 'incomeBeforeTax': '1825000000', 'incomeTaxExpense': '22000000', 'interestAndDebtExpense': '172000000', 'netIncomeFromContinuingOperations': '1735000000', 'comprehensiveIncomeNetOfTax': '1815000000', 'ebit': '1997000000', 'ebitda': '1823000000', 'netIncome': '1803000000'}, {'fiscalDateEnding': '2023-03-31', 'reportedCurrency': 'USD', 'grossProfit': '5122000000', 'totalRevenue': '9275000000', 'costOfRevenue': '4153000000', 'costofGoodsAndServicesSold': '4153000000', 'operatingIncome': '2090000000', 'sellingGeneralAndAdministrative': '614000000', 'researchAndDevelopment': '2210000000', 'operatingExpenses': '2824000000', 'investmentIncomeNet': '59000000', 'netInterestIncome': '-179000000', 'interestIncome': '59000000', 'interestExpense': '179000000', 'nonInterestIncome': 'None', 'otherNonOperatingIncome': '-18000000', 'depreciation': 'None', 'depreciationAndAmortization': '470000000', 'incomeBeforeTax': '1897000000', 'incomeTaxExpense': '193000000', 'interestAndDebtExpense': '179000000', 'netIncomeFromContinuingOperations': '1702000000', 'comprehensiveIncomeNetOfTax': '1829000000', 'ebit': '2076000000', 'ebitda': '2560000000', 'netIncome': '1704000000'}, {'fiscalDateEnding': '2022-12-31', 'reportedCurrency': 'USD', 'grossProfit': '5419000000', 'totalRevenue': '9463000000', 'costOfRevenue': '4044000000', 'costofGoodsAndServicesSold': '4044000000', 'operatingIncome': '2465000000', 'sellingGeneralAndAdministrative': '623000000', 'researchAndDevelopment': '2251000000', 'operatingExpenses': '2954000000', 'investmentIncomeNet': '55000000', 'netInterestIncome': '-170000000', 'interestIncome': '55000000', 'interestExpense': '170000000', 'nonInterestIncome': '-3000000', 'otherNonOperatingIncome': '76000000', 'depreciation': 'None', 'depreciationAndAmortization': '398000000', 'incomeBeforeTax': '2333000000', 'incomeTaxExpense': '98000000', 'interestAndDebtExpense': '170000000', 'netIncomeFromContinuingOperations': '2273000000', 'comprehensiveIncomeNetOfTax': '2550000000', 'ebit': '2503000000', 'ebitda': '2863000000', 'netIncome': '2235000000'}, {'fiscalDateEnding': '2022-09-30', 'reportedCurrency': 'USD', 'grossProfit': '6527000000', 'totalRevenue': '11395000000', 'costOfRevenue': '4868000000', 'costofGoodsAndServicesSold': '4868000000', 'operatingIncome': '3666000000', 'sellingGeneralAndAdministrative': '683000000', 'researchAndDevelopment': '2178000000', 'operatingExpenses': '3343000000', 'investmentIncomeNet': '32000000', 'netInterestIncome': '-145000000', 'interestIncome': '32000000', 'interestExpense': '145000000', 'nonInterestIncome': '-2000000', 'otherNonOperatingIncome': '-51000000', 'depreciation': 'None', 'depreciationAndAmortization': '1538000000', 'incomeBeforeTax': '3420000000', 'incomeTaxExpense': '547000000', 'interestAndDebtExpense': '145000000', 'netIncomeFromContinuingOperations': '2923000000', 'comprehensiveIncomeNetOfTax': '2633000000', 'ebit': '3565000000', 'ebitda': '5204000000', 'netIncome': '2873000000'}, {'fiscalDateEnding': '2022-06-30', 'reportedCurrency': 'USD', 'grossProfit': '6120000000', 'totalRevenue': '10936000000', 'costOfRevenue': '4816000000', 'costofGoodsAndServicesSold': '4816000000', 'operatingIncome': '4472000000', 'sellingGeneralAndAdministrative': '655000000', 'researchAndDevelopment': '2052000000', 'operatingExpenses': '2707000000', 'investmentIncomeNet': '22000000', 'netInterestIncome': '-70000000', 'interestIncome': '22000000', 'interestExpense': '70000000', 'nonInterestIncome': '13000000', 'otherNonOperatingIncome': '-6000000', 'depreciation': 'None', 'depreciationAndAmortization': '438000000', 'incomeBeforeTax': '4239000000', 'incomeTaxExpense': '509000000', 'interestAndDebtExpense': '70000000', 'netIncomeFromContinuingOperations': '3730000000', 'comprehensiveIncomeNetOfTax': '3733000000', 'ebit': '4309000000', 'ebitda': '3781000000', 'netIncome': '3730000000'}, {'fiscalDateEnding': '2022-03-31', 'reportedCurrency': 'USD', 'grossProfit': '6516000000', 'totalRevenue': '11164000000', 'costOfRevenue': '4648000000', 'costofGoodsAndServicesSold': '4648000000', 'operatingIncome': '3858000000', 'sellingGeneralAndAdministrative': '624000000', 'researchAndDevelopment': '2034000000', 'operatingExpenses': '2658000000', 'investmentIncomeNet': '20000000', 'netInterestIncome': '-137000000', 'interestIncome': '20000000', 'interestExpense': '137000000', 'nonInterestIncome': '1000000', 'otherNonOperatingIncome': '6000000', 'depreciation': 'None', 'depreciationAndAmortization': '415000000', 'incomeBeforeTax': '3423000000', 'incomeTaxExpense': '489000000', 'interestAndDebtExpense': '137000000', 'netIncomeFromContinuingOperations': '2934000000', 'comprehensiveIncomeNetOfTax': '3091000000', 'ebit': '3560000000', 'ebitda': '4273000000', 'netIncome': '2934000000'}, {'fiscalDateEnding': '2021-12-31', 'reportedCurrency': 'USD', 'grossProfit': '6402000000', 'totalRevenue': '10705000000', 'costOfRevenue': '4303000000', 'costofGoodsAndServicesSold': '4303000000', 'operatingIncome': '3864000000', 'sellingGeneralAndAdministrative': '608000000', 'researchAndDevelopment': '1930000000', 'operatingExpenses': '2538000000', 'investmentIncomeNet': '17000000', 'netInterestIncome': '-139000000', 'interestIncome': '17000000', 'interestExpense': '139000000', 'nonInterestIncome': '7000000', 'otherNonOperatingIncome': '140000000', 'depreciation': 'None', 'depreciationAndAmortization': '406000000', 'incomeBeforeTax': '3865000000', 'incomeTaxExpense': '466000000', 'interestAndDebtExpense': '139000000', 'netIncomeFromContinuingOperations': '3399000000', 'comprehensiveIncomeNetOfTax': '3329000000', 'ebit': '4004000000', 'ebitda': '4410000000', 'netIncome': '3399000000'}, {'fiscalDateEnding': '2021-09-30', 'reportedCurrency': 'USD', 'grossProfit': '5399000000', 'totalRevenue': '9336000000', 'costOfRevenue': '3937000000', 'costofGoodsAndServicesSold': '3937000000', 'operatingIncome': '2902000000', 'sellingGeneralAndAdministrative': '618000000', 'researchAndDevelopment': '1879000000', 'operatingExpenses': '3039000000', 'investmentIncomeNet': '20000000', 'netInterestIncome': '-138000000', 'interestIncome': '20000000', 'interestExpense': '138000000', 'nonInterestIncome': '-3000000', 'otherNonOperatingIncome': '521000000', 'depreciation': 'None', 'depreciationAndAmortization': '425000000', 'incomeBeforeTax': '3285000000', 'incomeTaxExpense': '487000000', 'interestAndDebtExpense': '138000000', 'netIncomeFromContinuingOperations': '2798000000', 'comprehensiveIncomeNetOfTax': '2742000000', 'ebit': '3423000000', 'ebitda': '3848000000', 'netIncome': '2798000000'}, {'fiscalDateEnding': '2021-06-30', 'reportedCurrency': 'USD', 'grossProfit': '4656000000', 'totalRevenue': '8060000000', 'costOfRevenue': '3404000000', 'costofGoodsAndServicesSold': '3404000000', 'operatingIncome': '2195000000', 'sellingGeneralAndAdministrative': '597000000', 'researchAndDevelopment': '1864000000', 'operatingExpenses': '2461000000', 'investmentIncomeNet': '21000000', 'netInterestIncome': '-138000000', 'interestIncome': '21000000', 'interestExpense': '138000000', 'nonInterestIncome': '-3000000', 'otherNonOperatingIncome': '200000000', 'depreciation': 'None', 'depreciationAndAmortization': '406000000', 'incomeBeforeTax': '2257000000', 'incomeTaxExpense': '230000000', 'interestAndDebtExpense': '138000000', 'netIncomeFromContinuingOperations': '2027000000', 'comprehensiveIncomeNetOfTax': '1930000000', 'ebit': '2395000000', 'ebitda': '2801000000', 'netIncome': '2027000000'}, {'fiscalDateEnding': '2021-03-31', 'reportedCurrency': 'USD', 'grossProfit': '4503000000', 'totalRevenue': '7935000000', 'costOfRevenue': '3432000000', 'costofGoodsAndServicesSold': '3432000000', 'operatingIncome': '2166000000', 'sellingGeneralAndAdministrative': '557000000', 'researchAndDevelopment': '1780000000', 'operatingExpenses': '2337000000', 'investmentIncomeNet': '22000000', 'netInterestIncome': '-141000000', 'interestIncome': '22000000', 'interestExpense': '141000000', 'nonInterestIncome': '-12000000', 'otherNonOperatingIncome': '104000000', 'depreciation': 'None', 'depreciationAndAmortization': '387000000', 'incomeBeforeTax': '2129000000', 'incomeTaxExpense': '367000000', 'interestAndDebtExpense': '141000000', 'netIncomeFromContinuingOperations': '1762000000', 'comprehensiveIncomeNetOfTax': '1750000000', 'ebit': '2270000000', 'ebitda': '2657000000', 'netIncome': '1762000000'}, {'fiscalDateEnding': '2020-12-31', 'reportedCurrency': 'USD', 'grossProfit': '4746000000', 'totalRevenue': '8235000000', 'costOfRevenue': '3489000000', 'costofGoodsAndServicesSold': '3489000000', 'operatingIncome': '2526000000', 'sellingGeneralAndAdministrative': '567000000', 'researchAndDevelopment': '1653000000', 'operatingExpenses': '2220000000', 'investmentIncomeNet': '21000000', 'netInterestIncome': '-141000000', 'interestIncome': '21000000', 'interestExpense': '141000000', 'nonInterestIncome': '-14000000', 'otherNonOperatingIncome': '219000000', 'depreciation': 'None', 'depreciationAndAmortization': '364000000', 'incomeBeforeTax': '2604000000', 'incomeTaxExpense': '149000000', 'interestAndDebtExpense': '141000000', 'netIncomeFromContinuingOperations': '2455000000', 'comprehensiveIncomeNetOfTax': '2541000000', 'ebit': '2745000000', 'ebitda': '3109000000', 'netIncome': '2455000000'}, {'fiscalDateEnding': '2020-09-30', 'reportedCurrency': 'USD', 'grossProfit': '5580000000', 'totalRevenue': '8346000000', 'costOfRevenue': '2766000000', 'costofGoodsAndServicesSold': '2766000000', 'operatingIncome': '3452000000', 'sellingGeneralAndAdministrative': '551000000', 'researchAndDevelopment': '1582000000', 'operatingExpenses': '2749000000', 'investmentIncomeNet': '21000000', 'netInterestIncome': '-166000000', 'interestIncome': '21000000', 'interestExpense': '166000000', 'nonInterestIncome': '-4000000', 'otherNonOperatingIncome': '19000000', 'depreciation': 'None', 'depreciationAndAmortization': '339000000', 'incomeBeforeTax': '3306000000', 'incomeTaxExpense': '346000000', 'interestAndDebtExpense': '149000000', 'netIncomeFromContinuingOperations': '0', 'comprehensiveIncomeNetOfTax': '3055000000', 'ebit': '3472000000', 'ebitda': '3811000000', 'netIncome': '2960000000'}, {'fiscalDateEnding': '2020-06-30', 'reportedCurrency': 'USD', 'grossProfit': '2813000000', 'totalRevenue': '4893000000', 'costOfRevenue': '2080000000', 'costofGoodsAndServicesSold': '2080000000', 'operatingIncome': '782000000', 'sellingGeneralAndAdministrative': '511000000', 'researchAndDevelopment': '1520000000', 'operatingExpenses': '2008000000', 'investmentIncomeNet': '30000000', 'netInterestIncome': '-143000000', 'interestIncome': '30000000', 'interestExpense': '143000000', 'nonInterestIncome': '-6000000', 'otherNonOperatingIncome': '229000000', 'depreciation': 'None', 'depreciationAndAmortization': '363000000', 'incomeBeforeTax': '868000000', 'incomeTaxExpense': '23000000', 'interestAndDebtExpense': '143000000', 'netIncomeFromContinuingOperations': '3805000000', 'comprehensiveIncomeNetOfTax': '902000000', 'ebit': '1011000000', 'ebitda': '1374000000', 'netIncome': '845000000'}, {'fiscalDateEnding': '2020-03-31', 'reportedCurrency': 'USD', 'grossProfit': '2919000000', 'totalRevenue': '5216000000', 'costOfRevenue': '2297000000', 'costofGoodsAndServicesSold': '2297000000', 'operatingIncome': '991000000', 'sellingGeneralAndAdministrative': '483000000', 'researchAndDevelopment': '1468000000', 'operatingExpenses': '1928000000', 'investmentIncomeNet': '47000000', 'netInterestIncome': '-146000000', 'interestIncome': '47000000', 'interestExpense': '146000000', 'nonInterestIncome': '6000000', 'otherNonOperatingIncome': '-247000000', 'depreciation': 'None', 'depreciationAndAmortization': '340000000', 'incomeBeforeTax': '598000000', 'incomeTaxExpense': '130000000', 'interestAndDebtExpense': '146000000', 'netIncomeFromContinuingOperations': '468000000', 'comprehensiveIncomeNetOfTax': '386000000', 'ebit': '744000000', 'ebitda': '1084000000', 'netIncome': '468000000'}, {'fiscalDateEnding': '2019-12-31', 'reportedCurrency': 'USD', 'grossProfit': '2964000000', 'totalRevenue': '5077000000', 'costOfRevenue': '2113000000', 'costofGoodsAndServicesSold': '2113000000', 'operatingIncome': '1030000000', 'sellingGeneralAndAdministrative': '528000000', 'researchAndDevelopment': '1406000000', 'operatingExpenses': '1934000000', 'investmentIncomeNet': '69000000', 'netInterestIncome': '-148000000', 'interestIncome': '69000000', 'interestExpense': '148000000', 'nonInterestIncome': '-3000000', 'otherNonOperatingIncome': '65000000', 'depreciation': 'None', 'depreciationAndAmortization': '351000000', 'incomeBeforeTax': '947000000', 'incomeTaxExpense': '22000000', 'interestAndDebtExpense': '148000000', 'netIncomeFromContinuingOperations': '925000000', 'comprehensiveIncomeNetOfTax': '962000000', 'ebit': '1095000000', 'ebitda': '1446000000', 'netIncome': '925000000'}, {'fiscalDateEnding': '2019-09-30', 'reportedCurrency': 'USD', 'grossProfit': '2696000000', 'totalRevenue': '4814000000', 'costOfRevenue': '2118000000', 'costofGoodsAndServicesSold': '2118000000', 'operatingIncome': '701000000', 'sellingGeneralAndAdministrative': '549000000', 'researchAndDevelopment': '1441000000', 'operatingExpenses': '2723000000', 'investmentIncomeNet': '79000000', 'netInterestIncome': '-150000000', 'interestIncome': '79000000', 'interestExpense': '150000000', 'nonInterestIncome': '11000000', 'otherNonOperatingIncome': '64000000', 'depreciation': 'None', 'depreciationAndAmortization': '350000000', 'incomeBeforeTax': '614000000', 'incomeTaxExpense': '108000000', 'interestAndDebtExpense': '150000000', 'netIncomeFromContinuingOperations': '701000000', 'comprehensiveIncomeNetOfTax': '411000000', 'ebit': '764000000', 'ebitda': '1114000000', 'netIncome': '506000000'}, {'fiscalDateEnding': '2019-06-30', 'reportedCurrency': 'USD', 'grossProfit': '7521000000', 'totalRevenue': '9635000000', 'costOfRevenue': '2114000000', 'costofGoodsAndServicesSold': '2114000000', 'operatingIncome': '5317000000', 'sellingGeneralAndAdministrative': '547000000', 'researchAndDevelopment': '1380000000', 'operatingExpenses': '1927000000', 'investmentIncomeNet': '81000000', 'netInterestIncome': '-160000000', 'interestIncome': '81000000', 'interestExpense': '160000000', 'nonInterestIncome': '-5000000', 'otherNonOperatingIncome': '344000000', 'depreciation': 'None', 'depreciationAndAmortization': '353000000', 'incomeBeforeTax': '5501000000', 'incomeTaxExpense': '3352000000', 'interestAndDebtExpense': '160000000', 'netIncomeFromContinuingOperations': '2149000000', 'comprehensiveIncomeNetOfTax': '2171000000', 'ebit': '5661000000', 'ebitda': '6014000000', 'netIncome': '2149000000'}, {'fiscalDateEnding': '2019-03-31', 'reportedCurrency': 'USD', 'grossProfit': '2803000000', 'totalRevenue': '4982000000'

In [108]:
income_df = pd.DataFrame(income_data['annualReports'])

In [109]:
#Sales/Revenue,COGS, EBIT, Interest, Taxes, NetIncome
income = income_df[['fiscalDateEnding','totalRevenue','costOfRevenue', 'ebit', 'interestIncome', 'incomeBeforeTax','incomeTaxExpense', 'netIncome']]#, axis=1 )
#income = income_df[['ebit']]
income

,fiscalDateEnding,totalRevenue,costOfRevenue,ebit,interestIncome,incomeBeforeTax,incomeTaxExpense,netIncome
0,2022-09-30,44200000000,18635000000,15438000000,91000000,14948000000,2012000000,12936000000
1,2021-09-30,33566000000,14262000000,10833000000,83000000,10274000000,1231000000,9043000000
2,2020-09-30,23531000000,9255000000,6321000000,156000000,5719000000,521000000,5198000000
3,2019-09-30,24273000000,8599000000,8108000000,316000000,7481000000,3095000000,4386000000
4,2018-09-30,22611000000,10244000000,1160000000,625000000,392000000,5356000000,-4964000000

#### Updating Column Names ####

In [110]:
# Updating Column Names
income.columns = ['DateEnding', 'TotalRevenue','COGS', 'EBIT', 'Interest', 'IncomeBeforeTax',
       'IncomeTaxExpense', 'NetIncome']
income

,DateEnding,TotalRevenue,COGS,EBIT,Interest,IncomeBeforeTax,IncomeTaxExpense,NetIncome
0,2022-09-30,44200000000,18635000000,15438000000,91000000,14948000000,2012000000,12936000000
1,2021-09-30,33566000000,14262000000,10833000000,83000000,10274000000,1231000000,9043000000
2,2020-09-30,23531000000,9255000000,6321000000,156000000,5719000000,521000000,5198000000
3,2019-09-30,24273000000,8599000000,8108000000,316000000,7481000000,3095000000,4386000000
4,2018-09-30,22611000000,10244000000,1160000000,625000000,392000000,5356000000,-4964000000

##### Balance Sheet

In [111]:
#### API call for Balance sheet ####
url = f'https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol={company_tik}&apikey={api_key}&datatype=csv'
r = requests.get(url)
balance_sheet = r.json()

print(balance_sheet)

{'symbol': 'QCOM', 'annualReports': [{'fiscalDateEnding': '2022-09-30', 'reportedCurrency': 'USD', 'totalAssets': '49014000000', 'totalCurrentAssets': '20724000000', 'cashAndCashEquivalentsAtCarryingValue': '2773000000', 'cashAndShortTermInvestments': '9827000000', 'inventory': '6341000000', 'currentNetReceivables': '4208000000', 'totalNonCurrentAssets': '31915000000', 'propertyPlantEquipment': '5168000000', 'accumulatedDepreciationAmortizationPPE': '6602000000', 'intangibleAssets': '12390000000', 'intangibleAssetsExcludingGoodwill': '1882000000', 'goodwill': '10508000000', 'investments': '8348000000', 'longTermInvestments': '1294000000', 'shortTermInvestments': '7054000000', 'otherCurrentAssets': '1625000000', 'otherNonCurrentAssets': '7729000000', 'totalLiabilities': '31001000000', 'totalCurrentLiabilities': '11866000000', 'currentAccountsPayable': '3796000000', 'deferredRevenue': '513000000', 'currentDebt': '1945000000', 'shortTermDebt': '1446000000', 'totalNonCurrentLiabilities': '17945000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13537000000', 'currentLongTermDebt': '1446000000', 'longTermDebtNoncurrent': '13537000000', 'shortLongTermDebtTotal': '14983000000', 'otherCurrentLiabilities': '3689000000', 'otherNonCurrentLiabilities': '5454000000', 'totalShareholderEquity': '18013000000', 'treasuryStock': 'None', 'retainedEarnings': '17840000000', 'commonStock': '195000000', 'commonStockSharesOutstanding': '1121000000'}, {'fiscalDateEnding': '2021-09-30', 'reportedCurrency': 'USD', 'totalAssets': '41240000000', 'totalCurrentAssets': '20075000000', 'cashAndCashEquivalentsAtCarryingValue': '7116000000', 'cashAndShortTermInvestments': '17030000000', 'inventory': '3228000000', 'currentNetReceivables': '2225000000', 'totalNonCurrentAssets': '24843000000', 'propertyPlantEquipment': '4559000000', 'accumulatedDepreciationAmortizationPPE': '5895000000', 'intangibleAssets': '8704000000', 'intangibleAssetsExcludingGoodwill': '1458000000', 'goodwill': '7246000000', 'investments': '11179000000', 'longTermInvestments': '1265000000', 'shortTermInvestments': '9914000000', 'otherCurrentAssets': '854000000', 'otherNonCurrentAssets': '6311000000', 'totalLiabilities': '31290000000', 'totalCurrentLiabilities': '11951000000', 'currentAccountsPayable': '2750000000', 'deferredRevenue': '976000000', 'currentDebt': '2044000000', 'shortTermDebt': '1544000000', 'totalNonCurrentLiabilities': '18106000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13701000000', 'currentLongTermDebt': '1544000000', 'longTermDebtNoncurrent': '13701000000', 'shortLongTermDebtTotal': '15245000000', 'otherCurrentLiabilities': '5014000000', 'otherNonCurrentLiabilities': '5274000000', 'totalShareholderEquity': '9950000000', 'treasuryStock': 'None', 'retainedEarnings': '9822000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1125000000'}, {'fiscalDateEnding': '2020-09-30', 'reportedCurrency': 'USD', 'totalAssets': '35594000000', 'totalCurrentAssets': '18519000000', 'cashAndCashEquivalentsAtCarryingValue': '6707000000', 'cashAndShortTermInvestments': '11214000000', 'inventory': '2598000000', 'currentNetReceivables': '2698000000', 'totalNonCurrentAssets': '20187000000', 'propertyPlantEquipment': '3711000000', 'accumulatedDepreciationAmortizationPPE': '5134000000', 'intangibleAssets': '7976000000', 'intangibleAssetsExcludingGoodwill': '1653000000', 'goodwill': '6323000000', 'investments': '9684000000', 'longTermInvestments': '1017000000', 'shortTermInvestments': '4507000000', 'otherCurrentAssets': '704000000', 'otherNonCurrentAssets': '4037000000', 'totalLiabilities': '29517000000', 'totalCurrentLiabilities': '8672000000', 'currentAccountsPayable': '2248000000', 'deferredRevenue': '1329000000', 'currentDebt': '500000000', 'shortTermDebt': '500000000', 'totalNonCurrentLiabilities': '19459000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '15226000000', 'currentLongTermDebt': '0', 'longTermDebtNoncurrent': '15226000000', 'shortLongTermDebtTotal': '15226000000', 'otherCurrentLiabilities': '4303000000', 'otherNonCurrentLiabilities': '4858000000', 'totalShareholderEquity': '6077000000', 'treasuryStock': 'None', 'retainedEarnings': '5284000000', 'commonStock': '586000000', 'commonStockSharesOutstanding': '1131000000'}, {'fiscalDateEnding': '2019-09-30', 'reportedCurrency': 'USD', 'totalAssets': '32957000000', 'totalCurrentAssets': '16765000000', 'cashAndCashEquivalentsAtCarryingValue': '11839000000', 'cashAndShortTermInvestments': '12260000000', 'inventory': '1400000000', 'currentNetReceivables': '1060000000', 'totalNonCurrentAssets': '18619000000', 'propertyPlantEquipment': '3081000000', 'accumulatedDepreciationAmortizationPPE': '4567000000', 'intangibleAssets': '8454000000', 'intangibleAssetsExcludingGoodwill': '2172000000', 'goodwill': '6282000000', 'investments': '1551000000', 'longTermInvestments': '1130000000', 'shortTermInvestments': '421000000', 'otherCurrentAssets': '634000000', 'otherNonCurrentAssets': '3461000000', 'totalLiabilities': '28048000000', 'totalCurrentLiabilities': '8935000000', 'currentAccountsPayable': '1368000000', 'deferredRevenue': '1725000000', 'currentDebt': '2496000000', 'shortTermDebt': '1997000000', 'totalNonCurrentLiabilities': '18085000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13437000000', 'currentLongTermDebt': '1997000000', 'longTermDebtNoncurrent': '13437000000', 'shortLongTermDebtTotal': '15434000000', 'otherCurrentLiabilities': '3458000000', 'otherNonCurrentLiabilities': '4516000000', 'totalShareholderEquity': '4909000000', 'treasuryStock': 'None', 'retainedEarnings': '4466000000', 'commonStock': '343000000', 'commonStockSharesOutstanding': '1145000000'}, {'fiscalDateEnding': '2018-09-30', 'reportedCurrency': 'USD', 'totalAssets': '32718000000', 'totalCurrentAssets': '17384000000', 'cashAndCashEquivalentsAtCarryingValue': '11777000000', 'cashAndShortTermInvestments': '12088000000', 'inventory': '1693000000', 'currentNetReceivables': '2848000000', 'totalNonCurrentAssets': '16389000000', 'propertyPlantEquipment': '2975000000', 'accumulatedDepreciationAmortizationPPE': '4486000000', 'intangibleAssets': '9453000000', 'intangibleAssetsExcludingGoodwill': '2955000000', 'goodwill': '6498000000', 'investments': '1577000000', 'longTermInvestments': '1087000000', 'shortTermInvestments': '311000000', 'otherCurrentAssets': '699000000', 'otherNonCurrentAssets': 'None', 'totalLiabilities': '31911000000', 'totalCurrentLiabilities': '11389000000', 'currentAccountsPayable': '1825000000', 'deferredRevenue': 'None', 'currentDebt': '1005000000', 'shortTermDebt': '1005000000', 'totalNonCurrentLiabilities': '3828000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '15365000000', 'currentLongTermDebt': '0', 'longTermDebtNoncurrent': '15365000000', 'shortLongTermDebtTotal': '15365000000', 'otherCurrentLiabilities': '7906000000', 'otherNonCurrentLiabilities': '1225000000', 'totalShareholderEquity': '807000000', 'treasuryStock': 'None', 'retainedEarnings': '663000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1219000000'}], 'quarterlyReports': [{'fiscalDateEnding': '2023-06-30', 'reportedCurrency': 'USD', 'totalAssets': '49002000000', 'totalCurrentAssets': '20476000000', 'cashAndCashEquivalentsAtCarryingValue': '6087000000', 'cashAndShortTermInvestments': '8631000000', 'inventory': '6628000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '28526000000', 'propertyPlantEquipment': '5216000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '12209000000', 'intangibleAssetsExcludingGoodwill': '1618000000', 'goodwill': '10591000000', 'investments': '2544000000', 'longTermInvestments': 'None', 'shortTermInvestments': '2544000000', 'otherCurrentAssets': '1050000000', 'otherNonCurrentAssets': '8110000000', 'totalLiabilities': '28332000000', 'totalCurrentLiabilities': '8463000000', 'currentAccountsPayable': '1744000000', 'deferredRevenue': '341000000', 'currentDebt': '914000000', 'shortTermDebt': '914000000', 'totalNonCurrentLiabilities': '1226000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '14530000000', 'currentLongTermDebt': '914000000', 'longTermDebtNoncurrent': '14900000000', 'shortLongTermDebtTotal': '14530000000', 'otherCurrentLiabilities': '3710000000', 'otherNonCurrentLiabilities': '5247000000', 'totalShareholderEquity': '20670000000', 'treasuryStock': 'None', 'retainedEarnings': '20163000000', 'commonStock': '77000000', 'commonStockSharesOutstanding': '1115000000'}, {'fiscalDateEnding': '2023-03-31', 'reportedCurrency': 'USD', 'totalAssets': '48362000000', 'totalCurrentAssets': '19073000000', 'cashAndCashEquivalentsAtCarryingValue': '3488000000', 'cashAndShortTermInvestments': '6676000000', 'inventory': '6858000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '29289000000', 'propertyPlantEquipment': '5281000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '12306000000', 'intangibleAssetsExcludingGoodwill': '1727000000', 'goodwill': '10579000000', 'investments': '3188000000', 'longTermInvestments': 'None', 'shortTermInvestments': '3188000000', 'otherCurrentAssets': '1032000000', 'otherNonCurrentAssets': '7974000000', 'totalLiabilities': '28664000000', 'totalCurrentLiabilities': '7866000000', 'currentAccountsPayable': '1430000000', 'deferredRevenue': '381000000', 'currentDebt': '499000000', 'shortTermDebt': '499000000', 'totalNonCurrentLiabilities': '1304000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '15486000000', 'currentLongTermDebt': '499000000', 'longTermDebtNoncurrent': '15100000000', 'shortLongTermDebtTotal': '15486000000', 'otherCurrentLiabilities': '3785000000', 'otherNonCurrentLiabilities': '5208000000', 'totalShareholderEquity': '19698000000', 'treasuryStock': 'None', 'retainedEarnings': '19280000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1114000000'}, {'fiscalDateEnding': '2022-12-31', 'reportedCurrency': 'USD', 'totalAssets': '50014000000', 'totalCurrentAssets': '21098000000', 'cashAndCashEquivalentsAtCarryingValue': '4808000000', 'cashAndShortTermInvestments': '11529000000', 'inventory': '6932000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '28916000000', 'propertyPlantEquipment': '5215000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '12362000000', 'intangibleAssetsExcludingGoodwill': '1796000000', 'goodwill': '10566000000', 'investments': '6721000000', 'longTermInvestments': 'None', 'shortTermInvestments': '6721000000', 'otherCurrentAssets': '1247000000', 'otherNonCurrentAssets': '8048000000', 'totalLiabilities': '31204000000', 'totalCurrentLiabilities': '10081000000', 'currentAccountsPayable': '2562000000', 'deferredRevenue': '394000000', 'currentDebt': '1446000000', 'shortTermDebt': '1446000000', 'totalNonCurrentLiabilities': '17119000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '15431000000', 'currentLongTermDebt': '1446000000', 'longTermDebtNoncurrent': '15431000000', 'shortLongTermDebtTotal': '16877000000', 'otherCurrentLiabilities': '3678000000', 'otherNonCurrentLiabilities': '5587000000', 'totalShareholderEquity': '18810000000', 'treasuryStock': 'None', 'retainedEarnings': '18517000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1119000000'}, {'fiscalDateEnding': '2022-09-30', 'reportedCurrency': 'USD', 'totalAssets': '49014000000', 'totalCurrentAssets': '20724000000', 'cashAndCashEquivalentsAtCarryingValue': '2773000000', 'cashAndShortTermInvestments': '9827000000', 'inventory': '6341000000', 'currentNetReceivables': '4208000000', 'totalNonCurrentAssets': '31915000000', 'propertyPlantEquipment': '5168000000', 'accumulatedDepreciationAmortizationPPE': '6602000000', 'intangibleAssets': '12390000000', 'intangibleAssetsExcludingGoodwill': '1882000000', 'goodwill': '10508000000', 'investments': '8348000000', 'longTermInvestments': '1294000000', 'shortTermInvestments': '7054000000', 'otherCurrentAssets': '1625000000', 'otherNonCurrentAssets': '7729000000', 'totalLiabilities': '31001000000', 'totalCurrentLiabilities': '11866000000', 'currentAccountsPayable': '3796000000', 'deferredRevenue': '513000000', 'currentDebt': '1945000000', 'shortTermDebt': '1446000000', 'totalNonCurrentLiabilities': '17945000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13537000000', 'currentLongTermDebt': '1446000000', 'longTermDebtNoncurrent': '13537000000', 'shortLongTermDebtTotal': '14983000000', 'otherCurrentLiabilities': '3689000000', 'otherNonCurrentLiabilities': '5454000000', 'totalShareholderEquity': '18013000000', 'treasuryStock': 'None', 'retainedEarnings': '17840000000', 'commonStock': '195000000', 'commonStockSharesOutstanding': '1121000000'}, {'fiscalDateEnding': '2022-06-30', 'reportedCurrency': 'USD', 'totalAssets': '47020000000', 'totalCurrentAssets': '18999000000', 'cashAndCashEquivalentsAtCarryingValue': '2676000000', 'cashAndShortTermInvestments': '10774000000', 'inventory': '5418000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '28021000000', 'propertyPlantEquipment': '5038000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '12673000000', 'intangibleAssetsExcludingGoodwill': '1954000000', 'goodwill': '10719000000', 'investments': '8098000000', 'longTermInvestments': 'None', 'shortTermInvestments': '8098000000', 'otherCurrentAssets': '1979000000', 'otherNonCurrentAssets': '7616000000', 'totalLiabilities': '30972000000', 'totalCurrentLiabilities': '11829000000', 'currentAccountsPayable': '3752000000', 'deferredRevenue': '643000000', 'currentDebt': '1945000000', 'shortTermDebt': '1445000000', 'totalNonCurrentLiabilities': '15388000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13600000000', 'currentLongTermDebt': '1445000000', 'longTermDebtNoncurrent': '13600000000', 'shortLongTermDebtTotal': '15045000000', 'otherCurrentLiabilities': '3414000000', 'otherNonCurrentLiabilities': '5363000000', 'totalShareholderEquity': '16048000000', 'treasuryStock': 'None', 'retainedEarnings': '15830000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1122000000'}, {'fiscalDateEnding': '2022-03-31', 'reportedCurrency': 'USD', 'totalAssets': '44302000000', 'totalCurrentAssets': '21610000000', 'cashAndCashEquivalentsAtCarryingValue': '7173000000', 'cashAndShortTermInvestments': '15515000000', 'inventory': '4555000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '22692000000', 'propertyPlantEquipment': '4893000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '8519000000', 'intangibleAssetsExcludingGoodwill': '1258000000', 'goodwill': '7261000000', 'investments': '8342000000', 'longTermInvestments': 'None', 'shortTermInvestments': '8342000000', 'otherCurrentAssets': '1425000000', 'otherNonCurrentAssets': '7735000000', 'totalLiabilities': '30974000000', 'totalCurrentLiabilities': '13432000000', 'currentAccountsPayable': '3724000000', 'deferredRevenue': '762000000', 'currentDebt': '3485000000', 'shortTermDebt': '500000000', 'totalNonCurrentLiabilities': '1707000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '12195000000', 'currentLongTermDebt': '2985000000', 'longTermDebtNoncurrent': '15500000000', 'shortLongTermDebtTotal': '12695000000', 'otherCurrentLiabilities': '4565000000', 'otherNonCurrentLiabilities': '5119000000', 'totalShareholderEquity': '13328000000', 'treasuryStock': 'None', 'retainedEarnings': '13113000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1122000000'}, {'fiscalDateEnding': '2021-12-31', 'reportedCurrency': 'USD', 'totalAssets': '42820000000', 'totalCurrentAssets': '20222000000', 'cashAndCashEquivalentsAtCarryingValue': '6607000000', 'cashAndShortTermInvestments': '15313000000', 'inventory': '3861000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '22598000000', 'propertyPlantEquipment': '4723000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '8637000000', 'intangibleAssetsExcludingGoodwill': '1373000000', 'goodwill': '7264000000', 'investments': '8706000000', 'longTermInvestments': 'None', 'shortTermInvestments': '8706000000', 'otherCurrentAssets': '1019000000', 'otherNonCurrentAssets': '7784000000', 'totalLiabilities': '31487000000', 'totalCurrentLiabilities': '12273000000', 'currentAccountsPayable': '3526000000', 'deferredRevenue': '861000000', 'currentDebt': '2042000000', 'shortTermDebt': '2042000000', 'totalNonCurrentLiabilities': '1944000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13708000000', 'currentLongTermDebt': '2042000000', 'longTermDebtNoncurrent': '16900000000', 'shortLongTermDebtTotal': '13708000000', 'otherCurrentLiabilities': '4661000000', 'otherNonCurrentLiabilities': '5249000000', 'totalShareholderEquity': '11333000000', 'treasuryStock': 'None', 'retainedEarnings': '11275000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1125000000'}, {'fiscalDateEnding': '2021-09-30', 'reportedCurrency': 'USD', 'totalAssets': '41240000000', 'totalCurrentAssets': '20075000000', 'cashAndCashEquivalentsAtCarryingValue': '7116000000', 'cashAndShortTermInvestments': '17030000000', 'inventory': '3228000000', 'currentNetReceivables': '2225000000', 'totalNonCurrentAssets': '24843000000', 'propertyPlantEquipment': '4559000000', 'accumulatedDepreciationAmortizationPPE': '5895000000', 'intangibleAssets': '8704000000', 'intangibleAssetsExcludingGoodwill': '1458000000', 'goodwill': '7246000000', 'investments': '11179000000', 'longTermInvestments': '1265000000', 'shortTermInvestments': '9914000000', 'otherCurrentAssets': '854000000', 'otherNonCurrentAssets': '6311000000', 'totalLiabilities': '31290000000', 'totalCurrentLiabilities': '11951000000', 'currentAccountsPayable': '2750000000', 'deferredRevenue': '976000000', 'currentDebt': '2044000000', 'shortTermDebt': '1544000000', 'totalNonCurrentLiabilities': '18106000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13701000000', 'currentLongTermDebt': '1544000000', 'longTermDebtNoncurrent': '13701000000', 'shortLongTermDebtTotal': '15245000000', 'otherCurrentLiabilities': '5014000000', 'otherNonCurrentLiabilities': '5274000000', 'totalShareholderEquity': '9950000000', 'treasuryStock': 'None', 'retainedEarnings': '9822000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1125000000'}, {'fiscalDateEnding': '2021-06-30', 'reportedCurrency': 'USD', 'totalAssets': '38769000000', 'totalCurrentAssets': '19693000000', 'cashAndCashEquivalentsAtCarryingValue': '7399000000', 'cashAndShortTermInvestments': '12907000000', 'inventory': '3133000000', 'currentNetReceivables': 'None', 'totalNonCurrentAssets': '19076000000', 'propertyPlantEquipment': '4424000000', 'accumulatedDepreciationAmortizationPPE': 'None', 'intangibleAssets': '8771000000', 'intangibleAssetsExcludingGoodwill': '1542000000', 'goodwill': '7229000000', 'investments': '10713000000', 'longTermInvestments': '0', 'shortTermInvestments': '5508000000', 'otherCurrentAssets': '701000000', 'otherNonCurrentAssets': '4431000000', 'totalLiabilities': '30592000000', 'totalCurrentLiabilities': '11460000000', 'currentAccountsPayable': '2709000000', 'deferredRevenue': '1093000000', 'currentDebt': '2045000000', 'shortTermDebt': '500000000', 'totalNonCurrentLiabilities': '2189000000', 'capitalLeaseObligations': 'None', 'longTermDebt': '13695000000', 'currentLongTermDebt': '1545000000', 'longTermDebtNoncurrent': '17000000000', 'shortLongTermDebtTotal': '14195000000', 'otherCurrentLiabilities': '4585000000', 'otherNonCurrentLiabilities': '3248000000', 'totalShareholderEquity': '8177000000', 'treasuryStock': 'None', 'retainedEarnings': '7993000000', 'commonStock': 'None', 'commonStockSharesOutstanding': '1128000000'}, {'fiscalDateEnding': '2021-03-31', 'reportedCurrency': 'USD', 'totalAssets': '37168000000', 'totalCurrentAssets': '18299000000', 'cashAndCashEquivalentsAtCarryingValue': '6000000000', 'cashAndShortTermInvestments': '11526000000', 'inventory': '2668000000', 'curre

In [112]:
balance_sheet = pd.DataFrame(balance_sheet['annualReports'])

In [113]:
balance_sheet

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,...,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
0,2022-09-30,USD,49014000000,20724000000,2773000000,9827000000,6341000000,4208000000,31915000000,5168000000,...,1446000000,13537000000,14983000000,3689000000,5454000000,18013000000,None,17840000000,195000000,1121000000
1,2021-09-30,USD,41240000000,20075000000,7116000000,17030000000,3228000000,2225000000,24843000000,4559000000,...,1544000000,13701000000,15245000000,5014000000,5274000000,9950000000,None,9822000000,None,1125000000
2,2020-09-30,USD,35594000000,18519000000,6707000000,11214000000,2598000000,2698000000,20187000000,3711000000,...,0,15226000000,15226000000,4303000000,4858000000,6077000000,None,5284000000,586000000,1131000000
3,2019-09-30,USD,32957000000,16765000000,11839000000,12260000000,1400000000,1060000000,18619000000,3081000000,...,1997000000,13437000000,15434000000,3458000000,4516000000,4909000000,None,4466000000,343000000,1145000000
4,2018-09-30,USD,32718000000,17384000000,11777000000,12088000000,1693000000,2848000000,16389000000,2975000000,...,0,15365000000,15365000000,7906000000,1225000000,807000000,None,663000000,None,1219000000

In [114]:
balance_sheet_fetch = balance_sheet[['inventory', 'currentNetReceivables', 'cashAndCashEquivalentsAtCarryingValue', 'totalCurrentAssets',\
                                    'shortTermDebt', 'longTermDebt', 'propertyPlantEquipment', 'totalAssets',\
                                   'totalCurrentLiabilities', 'totalLiabilities', 'totalShareholderEquity']]
balance_sheet_fetch

,inventory,currentNetReceivables,cashAndCashEquivalentsAtCarryingValue,totalCurrentAssets,shortTermDebt,longTermDebt,propertyPlantEquipment,totalAssets,totalCurrentLiabilities,totalLiabilities,totalShareholderEquity
0,6341000000,4208000000,2773000000,20724000000,1446000000,13537000000,5168000000,49014000000,11866000000,31001000000,18013000000
1,3228000000,2225000000,7116000000,20075000000,1544000000,13701000000,4559000000,41240000000,11951000000,31290000000,9950000000
2,2598000000,2698000000,6707000000,18519000000,500000000,15226000000,3711000000,35594000000,8672000000,29517000000,6077000000
3,1400000000,1060000000,11839000000,16765000000,1997000000,13437000000,3081000000,32957000000,8935000000,28048000000,4909000000
4,1693000000,2848000000,11777000000,17384000000,1005000000,15365000000,2975000000,32718000000,11389000000,31911000000,807000000

In [115]:
balance_sheet_fetch.columns = ['Inventory','Net Receivables','Cash','Total Current Assets',\
                   'Short Long Term Debt', 'Long Term Debt','Net Tangible Assets','Total Assets'\
                  ,'Total Current Liabilities', 'Total Liab','Total Stockholder Equity']
balance_sheet_fetch

,Inventory,Net Receivables,Cash,Total Current Assets,Short Long Term Debt,Long Term Debt,Net Tangible Assets,Total Assets,Total Current Liabilities,Total Liab,Total Stockholder Equity
0,6341000000,4208000000,2773000000,20724000000,1446000000,13537000000,5168000000,49014000000,11866000000,31001000000,18013000000
1,3228000000,2225000000,7116000000,20075000000,1544000000,13701000000,4559000000,41240000000,11951000000,31290000000,9950000000
2,2598000000,2698000000,6707000000,18519000000,500000000,15226000000,3711000000,35594000000,8672000000,29517000000,6077000000
3,1400000000,1060000000,11839000000,16765000000,1997000000,13437000000,3081000000,32957000000,8935000000,28048000000,4909000000
4,1693000000,2848000000,11777000000,17384000000,1005000000,15365000000,2975000000,32718000000,11389000000,31911000000,807000000

In [116]:
balance = balance_sheet_fetch
balance

,Inventory,Net Receivables,Cash,Total Current Assets,Short Long Term Debt,Long Term Debt,Net Tangible Assets,Total Assets,Total Current Liabilities,Total Liab,Total Stockholder Equity
0,6341000000,4208000000,2773000000,20724000000,1446000000,13537000000,5168000000,49014000000,11866000000,31001000000,18013000000
1,3228000000,2225000000,7116000000,20075000000,1544000000,13701000000,4559000000,41240000000,11951000000,31290000000,9950000000
2,2598000000,2698000000,6707000000,18519000000,500000000,15226000000,3711000000,35594000000,8672000000,29517000000,6077000000
3,1400000000,1060000000,11839000000,16765000000,1997000000,13437000000,3081000000,32957000000,8935000000,28048000000,4909000000
4,1693000000,2848000000,11777000000,17384000000,1005000000,15365000000,2975000000,32718000000,11389000000,31911000000,807000000

In [117]:
d1 = pd.concat([income, balance], axis=1)
d1

,DateEnding,TotalRevenue,COGS,EBIT,Interest,IncomeBeforeTax,IncomeTaxExpense,NetIncome,Inventory,Net Receivables,Cash,Total Current Assets,Short Long Term Debt,Long Term Debt,Net Tangible Assets,Total Assets,Total Current Liabilities,Total Liab,Total Stockholder Equity
0,2022-09-30,44200000000,18635000000,15438000000,91000000,14948000000,2012000000,12936000000,6341000000,4208000000,2773000000,20724000000,1446000000,13537000000,5168000000,49014000000,11866000000,31001000000,18013000000
1,2021-09-30,33566000000,14262000000,10833000000,83000000,10274000000,1231000000,9043000000,3228000000,2225000000,7116000000,20075000000,1544000000,13701000000,4559000000,41240000000,11951000000,31290000000,9950000000
2,2020-09-30,23531000000,9255000000,6321000000,156000000,5719000000,521000000,5198000000,2598000000,2698000000,6707000000,18519000000,500000000,15226000000,3711000000,35594000000,8672000000,29517000000,6077000000
3,2019-09-30,24273000000,8599000000,8108000000,316000000,7481000000,3095000000,4386000000,1400000000,1060000000,11839000000,16765000000,1997000000,13437000000,3081000000,32957000000,8935000000,28048000000,4909000000
4,2018-09-30,22611000000,10244000000,1160000000,625000000,392000000,5356000000,-4964000000,1693000000,2848000000,11777000000,17384000000,1005000000,15365000000,2975000000,32718000000,11389000000,31911000000,807000000

In [118]:
d1

,DateEnding,TotalRevenue,COGS,EBIT,Interest,IncomeBeforeTax,IncomeTaxExpense,NetIncome,Inventory,Net Receivables,Cash,Total Current Assets,Short Long Term Debt,Long Term Debt,Net Tangible Assets,Total Assets,Total Current Liabilities,Total Liab,Total Stockholder Equity
0,2022-09-30,44200000000,18635000000,15438000000,91000000,14948000000,2012000000,12936000000,6341000000,4208000000,2773000000,20724000000,1446000000,13537000000,5168000000,49014000000,11866000000,31001000000,18013000000
1,2021-09-30,33566000000,14262000000,10833000000,83000000,10274000000,1231000000,9043000000,3228000000,2225000000,7116000000,20075000000,1544000000,13701000000,4559000000,41240000000,11951000000,31290000000,9950000000
2,2020-09-30,23531000000,9255000000,6321000000,156000000,5719000000,521000000,5198000000,2598000000,2698000000,6707000000,18519000000,500000000,15226000000,3711000000,35594000000,8672000000,29517000000,6077000000
3,2019-09-30,24273000000,8599000000,8108000000,316000000,7481000000,3095000000,4386000000,1400000000,1060000000,11839000000,16765000000,1997000000,13437000000,3081000000,32957000000,8935000000,28048000000,4909000000
4,2018-09-30,22611000000,10244000000,1160000000,625000000,392000000,5356000000,-4964000000,1693000000,2848000000,11777000000,17384000000,1005000000,15365000000,2975000000,32718000000,11389000000,31911000000,807000000

#### Converting string to integer

In [119]:
d1_int = d1.apply(pd.to_numeric, errors='coerce') 

# replace None with zero
d1 = d1_int.fillna(0)
d1

,DateEnding,TotalRevenue,COGS,EBIT,Interest,IncomeBeforeTax,IncomeTaxExpense,NetIncome,Inventory,Net Receivables,Cash,Total Current Assets,Short Long Term Debt,Long Term Debt,Net Tangible Assets,Total Assets,Total Current Liabilities,Total Liab,Total Stockholder Equity
0,0.0,44200000000,18635000000,15438000000,91000000,14948000000,2012000000,12936000000,6341000000,4208000000,2773000000,20724000000,1446000000,13537000000,5168000000,49014000000,11866000000,31001000000,18013000000
1,0.0,33566000000,14262000000,10833000000,83000000,10274000000,1231000000,9043000000,3228000000,2225000000,7116000000,20075000000,1544000000,13701000000,4559000000,41240000000,11951000000,31290000000,9950000000
2,0.0,23531000000,9255000000,6321000000,156000000,5719000000,521000000,5198000000,2598000000,2698000000,6707000000,18519000000,500000000,15226000000,3711000000,35594000000,8672000000,29517000000,6077000000
3,0.0,24273000000,8599000000,8108000000,316000000,7481000000,3095000000,4386000000,1400000000,1060000000,11839000000,16765000000,1997000000,13437000000,3081000000,32957000000,8935000000,28048000000,4909000000
4,0.0,22611000000,10244000000,1160000000,625000000,392000000,5356000000,-4964000000,1693000000,2848000000,11777000000,17384000000,1005000000,15365000000,2975000000,32718000000,11389000000,31911000000,807000000

In [120]:
ratio = pd.DataFrame()

In [121]:
# Quick Ratio = Current Assets/Current Liabilities
ratio['Current Ratio'] = d1['Total Current Assets']/d1['Total Current Liabilities']
ratio

   Current Ratio
0       1.746503
1       1.679776
2       2.135494
3       1.876329
4       1.526385

In [122]:
# Quick Ratio = [Current Assets - Inventory]/ Current Liability
ratio['Quick Ratio'] = (d1['Total Current Assets'] - d1['Inventory'])/d1['Total Current Liabilities']
ratio

   Current Ratio  Quick Ratio
0       1.746503     1.212119
1       1.679776     1.409673
2       2.135494     1.835909
3       1.876329     1.719642
4       1.526385     1.377733

In [123]:
# Duration of Sales Operation
ratio['DSO'] = d1['Net Receivables']/(d1['TotalRevenue']/365)
ratio

   Current Ratio  Quick Ratio        DSO
0       1.746503     1.212119  34.749321
1       1.679776     1.409673  24.194870
2       2.135494     1.835909  41.849900
3       1.876329     1.719642  15.939521
4       1.526385     1.377733  45.974083

In [124]:
#Inventory Turnover
ratio['Inventory Turnover'] = d1['COGS']/d1['Inventory']
ratio

   Current Ratio  Quick Ratio        DSO  Inventory Turnover
0       1.746503     1.212119  34.749321            2.938811
1       1.679776     1.409673  24.194870            4.418216
2       2.135494     1.835909  41.849900            3.562356
3       1.876329     1.719642  15.939521            6.142143
4       1.526385     1.377733  45.974083            6.050797

In [125]:
# Total Assets Turnover
ratio['Total Assets Turnover'] = d1['TotalRevenue']/d1['Total Assets']
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover
0,1.746503,1.212119,34.749321,2.938811,0.901783
1,1.679776,1.409673,24.194870,4.418216,0.813919
2,2.135494,1.835909,41.849900,3.562356,0.661095
3,1.876329,1.719642,15.939521,6.142143,0.736505
4,1.526385,1.377733,45.974083,6.050797,0.691087

In [126]:
# Debt Ratio = (Short Long Term Deb + Long Term Debt + notes payable)/  Short Long Term Deb \
#+ Long Term Debt + notes payable+ common equity
# debt/debt+equity
d1['Debt'] = d1['Short Long Term Debt'] + d1['Long Term Debt']
ratio['Debt Ratio'] = d1['Debt']/(d1['Debt'] + d1['Total Stockholder Equity'])
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover,Debt Ratio
0,1.746503,1.212119,34.749321,2.938811,0.901783,0.454085
1,1.679776,1.409673,24.194870,4.418216,0.813919,0.605080
2,2.135494,1.835909,41.849900,3.562356,0.661095,0.721277
3,1.876329,1.719642,15.939521,6.142143,0.736505,0.758688
4,1.526385,1.377733,45.974083,6.050797,0.691087,0.953019

In [127]:
# Times Interest Earned = EBIT/Interest
ratio['TIE'] = d1['EBIT']/d1['Interest']
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover,Debt Ratio,TIE
0,1.746503,1.212119,34.749321,2.938811,0.901783,0.454085,169.648352
1,1.679776,1.409673,24.194870,4.418216,0.813919,0.605080,130.518072
2,2.135494,1.835909,41.849900,3.562356,0.661095,0.721277,40.519231
3,1.876329,1.719642,15.939521,6.142143,0.736505,0.758688,25.658228
4,1.526385,1.377733,45.974083,6.050797,0.691087,0.953019,1.856000

In [128]:
#Gross Profit Margin = EBIT/Sales
ratio['GPM%'] = 100*d1['EBIT']/d1['TotalRevenue']
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover,Debt Ratio,TIE,GPM%
0,1.746503,1.212119,34.749321,2.938811,0.901783,0.454085,169.648352,34.927602
1,1.679776,1.409673,24.194870,4.418216,0.813919,0.605080,130.518072,32.273729
2,2.135494,1.835909,41.849900,3.562356,0.661095,0.721277,40.519231,26.862437
3,1.876329,1.719642,15.939521,6.142143,0.736505,0.758688,25.658228,33.403370
4,1.526385,1.377733,45.974083,6.050797,0.691087,0.953019,1.856000,5.130246

In [129]:
#Net Profit Margin = net profit/Sales
ratio['NPM%'] = 100*d1['NetIncome']/d1['TotalRevenue']
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover,Debt Ratio,TIE,GPM%,NPM%
0,1.746503,1.212119,34.749321,2.938811,0.901783,0.454085,169.648352,34.927602,29.266968
1,1.679776,1.409673,24.194870,4.418216,0.813919,0.605080,130.518072,32.273729,26.940952
2,2.135494,1.835909,41.849900,3.562356,0.661095,0.721277,40.519231,26.862437,22.090009
3,1.876329,1.719642,15.939521,6.142143,0.736505,0.758688,25.658228,33.403370,18.069460
4,1.526385,1.377733,45.974083,6.050797,0.691087,0.953019,1.856000,5.130246,-21.953916

In [130]:
# Return on Total Assets = NetIncome/Assets
ratio['ROA%'] = 100*d1['NetIncome']/d1['Total Assets']
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover,Debt Ratio,TIE,GPM%,NPM%,ROA%
0,1.746503,1.212119,34.749321,2.938811,0.901783,0.454085,169.648352,34.927602,29.266968,26.392459
1,1.679776,1.409673,24.194870,4.418216,0.813919,0.605080,130.518072,32.273729,26.940952,21.927740
2,2.135494,1.835909,41.849900,3.562356,0.661095,0.721277,40.519231,26.862437,22.090009,14.603585
3,1.876329,1.719642,15.939521,6.142143,0.736505,0.758688,25.658228,33.403370,18.069460,13.308250
4,1.526385,1.377733,45.974083,6.050797,0.691087,0.953019,1.856000,5.130246,-21.953916,-15.172077

In [131]:
#DuPont Analysis ROE = Net Profit/Common Equity
ratio['ROE%'] = 100*d1['NetIncome']/d1['Total Stockholder Equity']
ratio

,Current Ratio,Quick Ratio,DSO,Inventory Turnover,Total Assets Turnover,Debt Ratio,TIE,GPM%,NPM%,ROA%,ROE%
0,1.746503,1.212119,34.749321,2.938811,0.901783,0.454085,169.648352,34.927602,29.266968,26.392459,71.814800
1,1.679776,1.409673,24.194870,4.418216,0.813919,0.605080,130.518072,32.273729,26.940952,21.927740,90.884422
2,2.135494,1.835909,41.849900,3.562356,0.661095,0.721277,40.519231,26.862437,22.090009,14.603585,85.535626
3,1.876329,1.719642,15.939521,6.142143,0.736505,0.758688,25.658228,33.403370,18.069460,13.308250,89.346099
4,1.526385,1.377733,45.974083,6.050797,0.691087,0.953019,1.856000,5.130246,-21.953916,-15.172077,-615.117720

In [132]:
ratio.style.set_caption(company_tik)

In [133]:
ratio = ratio.T
ratio

,0,1,2,3,4
Current Ratio,1.746503,1.679776,2.135494,1.876329,1.526385
Quick Ratio,1.212119,1.409673,1.835909,1.719642,1.377733
DSO,34.749321,24.194870,41.849900,15.939521,45.974083
Inventory Turnover,2.938811,4.418216,3.562356,6.142143,6.050797
Total Assets Turnover,0.901783,0.813919,0.661095,0.736505,0.691087
Debt Ratio,0.454085,0.605080,0.721277,0.758688,0.953019
TIE,169.648352,130.518072,40.519231,25.658228,1.856000
GPM%,34.927602,32.273729,26.862437,33.403370,5.130246
NPM%,29.266968,26.940952,22.090009,18.069460,-21.953916
ROA%,26.392459,21.927740,14.603585,13.308250,-15.172077
ROE%,71.814800,90.884422,85.535626,89.346099,-615.117720

In [134]:
ratio.index.name = ("year-"+ company_tik)
ratio.columns = income['DateEnding']
ratio

DateEnding,2022-09-30,2021-09-30,2020-09-30,2019-09-30,2018-09-30
year-QCOM,,,,,
Current Ratio,1.746503,1.679776,2.135494,1.876329,1.526385
Quick Ratio,1.212119,1.409673,1.835909,1.719642,1.377733
DSO,34.749321,24.194870,41.849900,15.939521,45.974083
Inventory Turnover,2.938811,4.418216,3.562356,6.142143,6.050797
Total Assets Turnover,0.901783,0.813919,0.661095,0.736505,0.691087
Debt Ratio,0.454085,0.605080,0.721277,0.758688,0.953019
TIE,169.648352,130.518072,40.519231,25.658228,1.856000
GPM%,34.927602,32.273729,26.862437,33.403370,5.130246
NPM%,29.266968,26.940952,22.090009,18.069460,-21.953916
ROA%,26.392459,21.927740,14.603585,13.308250,-15.172077
ROE%,71.814800,90.884422,85.535626,89.346099,-615.117720

#### CSV FILENAME

In [135]:
csv_name = 'APPLE_INTEL_NVIDIA_Qualcomm.csv'
ratio.to_csv(csv_name, mode='a') #, header= False)

In [136]:
df = pd.read_csv(csv_name)
print(df)

                year-AAPL           2022-09-30          2021-09-30  \
0           Current Ratio   0.8793560286267226  1.0745531195957954
1             Quick Ratio   0.8472353911496149  1.0221149018576519
2                     DSO    56.82256123577851  51.765251726454686
3      Inventory Turnover   50.270926000808736   35.70729483282675
4   Total Assets Turnover   1.1095434508369832  1.0346721671101589
5              Debt Ratio   0.7032456047881748  0.6640396187230417
6                     TIE   1151.2641509433963   39.34294759057334
7                    GPM%   31.179084152407913  30.798629850318857
8                    NPM%    25.49917347348089  26.070291762580815
9                    ROA%    28.29244092925685  26.974205275183618
10                   ROE%   196.95887275023682  150.07132667617688
11              year-NVDA           2023-01-29          2022-01-30
12          Current Ratio    3.515617857687033   6.650288350634371
13            Quick Ratio   2.7295444156635686   6.049365628604383
14                    DSO    51.78523763624231   63.06197518020361
15     Inventory Turnover    2.251986819150998    3.62341650671785
16  Total Assets Turnover   0.6549949006847652  0.6090931721999683
17             Debt Ratio   0.3313668542385188  0.2914425688268811
18                    TIE   16.640449438202246   350.9310344827586
19                   GPM%   16.471416919997033   37.81303410864234
20                   NPM%   16.193371394676355   36.23393029649996
21                   ROA%   10.606575688407556    22.0698395455677
22                   ROE%   19.763811592235644   36.64512250112731
23              year-INTC           2022-12-31          2021-12-31
24          Current Ratio   1.5676255636759446  2.1323283082077054
25            Quick Ratio   1.1563675944643135   1.739931541766805
26                    DSO   25.220672695798484   44.26619588578446
27     Inventory Turnover   3.4103901996370234   4.288882702301411
28  Total Assets Turnover  0.33942878480859734  0.4641639846561286
29             Debt Ratio   0.2928745729624207  0.2854178527552213
30                    TIE   14.025466893039049  154.86111111111111
31                   GPM%    13.36493504392422  28.528298024767167
32                   NPM%   12.965329795667438  25.417050455429333
33                   ROA%    4.400806137186098  11.797679417597948
34                   ROE%    7.901560789958885   20.82796070908157
35              year-QCOM           2022-09-30          2021-09-30
36          Current Ratio   1.7465026125063206  1.6797757509831812
37            Quick Ratio   1.2121186583515928  1.4096728307254622
38                    DSO    34.74932126696832  24.194869808735028
39     Inventory Turnover   2.9388109131051885     4.4182156133829
40  Total Assets Turnover   0.9017831639939609  0.8139185257032008
41             Debt Ratio  0.45408534367802156  0.6050803730898988
42                    TIE   169.64835164835165  130.51807228915663
43                   GPM%    34.92760180995475   32.27372936900435
44                   NPM%   29.266968325791854  26.940952153965323
45                   ROA%   26.392459297343617  21.927740058195926
46                   ROE%    71.81480042191751   90.88442211055276

             2020-09-30          2019-09-30           2018-09-30
0    1.3636044481554577   1.540125617208044   1.1329261875803294
1     1.325072111735236   1.501286441287198   1.0988018528582149
2    50.314108274861766    65.1542880303042    67.33249872926825
3    46.657227283920214  43.844861178762784     41.3943377148635
4    0.8386911524971595  0.7580084840893784   0.7262150522933899
5    0.6669911522465954   0.577608902664451   0.5363508513814665
6    18.592612277438214   13.97157831082443   13.391311994372142
7    25.755958209702477  27.012291600090414   28.668837892279598
8    21.134802423778357  21.534072751931035   22.414202074587248
9     17.72557180259843  16.323009842961632   16.277530931710984
10    87.86635853012748   61.06445053487755   55.560118342090774
11           2021-01-31          2020-01-26           2019-01-27
12    4.090445859872611   7.673766816143497    7.943566591422122
13   3.6252229299363057               7.125    6.758465011286682
14    53.16851574212893   55.39521890456127    44.58397666838223
15   3.4386637458926614   4.239019407558733   3.6812698412698412
16   0.5791740474453823   0.630551544903263     0.87706891363226
17  0.29187625754527163  0.1402606551602677  0.17546337157987643
18    80.57894736842105   16.97752808988764   29.073529411764707
19   27.544227886056973  27.679062099285584    33.91662377766341
20   25.979010494752625   25.60908591317091    35.52067249957111
21    15.04636865687194  16.147848686110308   31.154077640686126
22    25.64375776949032  22.910521140609635   44.326696638835365
23           2020-12-31          2019-12-31           2018-12-31
24    1.908742021491476  1.4002241147467502   1.7314447251293155
25   1.5683121919689746  1.0082922456297625    1.295200288704439
26    32.77622622882677  39.735334684456454   36.062576246860424
27    5.030259878960484   4.182067703568161   4.6861988142837445
28   0.5028643094629991  0.5204359673024523    0.544493330103233
29  0.32426778242677823  0.2966969147005445   0.2611819028556707
30    94.51102941176471  50.821946169772254    54.30365296803653
31   33.392653018809106   34.54793672240049    34.13706494438464
32   27.147199418060897  29.623374429994932    30.21600287047004
33   13.651357689217525  15.417069526237146   16.452412025351077
34    25.77800254091991  27.157308009909165   28.235183670184945
35           2020-09-30          2019-09-30           2018-09-30
36   2.1354935424354244  1.8763290430889759   1.5263851084379665
37    1.835908671586716  1.7196418578623391   1.3777329001668277
38    41.84990013174111   15.93952127878713    45.97408341072929
39   3.5623556581986144   6.142142857142857   6.0507974010632015
40   0.6610945664999719  0.7365051430652062   0.6910874747845223
41   0.7212768885015823   0.758688492356093   0.9530185713454037
42    40.51923076923077  25.658227848101266                1.856
43   26.862436785516977   33.40336999958802    5.130246340276856
44   22.090008924397605   18.06945989370906  -21.953916235460618
45   14.603584873855144  13.308250144127197  -15.172076532795403
46     85.5356261313148   89.34609900183337   -615.1177199504338